version: '3.2'
services:
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./react/build:/usr/share/nginx/html/
    ports:
      - "28080:80"
    environment:
      - NGINX_PORT=80
  node:
    image: node:16.15.1
    tty: true
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    working_dir: /home/node/app

